### ISSUE TITLE
The null object does not have a method 'dispatchEvent' when using MaterialRadio

### ISSUE THREAD

**Issue by st-clair-clarke** [jwashin/angular2-rbi-dart#3]
I have the following radio-button.
## .html

``` html
           <label class = "mdl-radio mdl-js-radio mdl-js-ripple-effect"
                   for = "female">
              <input type = "radio"
                     #female
                     [checked]="toggleOn"
                     (change)="onChange($event)"
                     class = "mdl-radio__button"
                     name = "gender"
                     value = "Female"
                     id = "female">
              <span class = "mdl-radio__label">Female</span>
            </label>
```
## .dart

``` dart
import 'dart:html' as dom;

 bool toggleOn = false;

  void onChange(dom.Event event) {
    dom.InputElement target = event.target;
    toggleOn = target.checked;
    print(target.value);
    print('toggleOn | ${toggleOn}');
  }
```

Running the application consistently gives the following error:

```
  Observatory listening at http://127.0.0.1:65347/
  Angular 2 is running in the development mode. Call enableProdMode() to enable the production  mode.
  Female
  toggleOn | true
  Uncaught Unhandled exception:
  The null object does not have a method 'dispatchEvent'.

  NoSuchMethodError: method not found: 'dispatchEvent'
  Receiver: null
  Arguments: [Instance of 'CustomEventImpl']
  #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
  #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
  #2      RadioBehavior.onChange (package:angular2_rbi/src/directives/material_radio.dart:72:14)
  #3      Function._apply (dart:core-patch/function_patch.dart:7)
  #4      Function.apply (dart:core-patch/function_patch.dart:28)
  #5      _CreateDartFunctionForInteropIgnoreThis.call (dart:js:1453)
  (anonymous function)
```

It seems to be an issue in the RadioBehaviour src.

Thanks for taking a look into it.
Cheers

Teddy

**Comment by jwashin** [comment]
I think I found the problem. Let me know if 0.0.9 version solves this.
- Jim

**Comment by jwashin** [comment]
I'm guessing the issue was when there is more than one radio group, and a radio widget was not finding an `input` element with a different `name`.
